vich_uploader:
  db_driver: orm

  mappings:
    vehicule_image:
      uri_prefix: /images/vehicules
      upload_destination: "%kernel.project_dir%/public/vehicule/images/vehicules"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
